<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix company-list">
    <h3><?php _e('List of links'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-condensed table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Status'); ?></th>
                <th><?php _e('Click'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $inventory) { ?>
                <tr>
                    <td><?php echo $this->escape($inventory['id']); ?></td>
                    <td><?php echo $this->escape($inventory['title']); ?></td>
                    <td><?php echo $this->escape($inventory['status_view']); ?></td>
                    <td><?php echo $this->escape($inventory['click']); ?></td>
                    <td>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', ['action' => 'update', 'id' => $inventory['id']]); ?>">
                            <i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                        <a class="btn btn-success btn-sm" title="<?php _e('Open'); ?>" href="<?php echo $this->escape($inventory['input']); ?>" target="_blank">
                            <i class="fa fa-eye"></i> <?php _e('Open'); ?>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('List is empty'); ?>
        </div>
    <?php } ?>
</div>